server:
  port: 8081
  servlet:
    context-path: /recombee-service
recombee:
  database-id: ${RECOMBEE_DB_ID}
  private-token: ${RECOMBEE_TOKEN}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    org.springframework.web: DEBUG
