server:
  port: 8081
  servlet:
    context-path: /recombee-service
recombee:
  database-id: ${RECOMBEE_DB_ID:dacn-dev}
  private-token: ${RECOMBEE_TOKEN:aG1RT8xXEINqWHlONh1PqDZYkLu8qV1oXe8mjRFIQaE0GC7WgD4gjSTmW6TOYIh2}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    org.springframework.web: DEBUG
