server:
  port: ${IDENTITY_PORT:8091}
  servlet:
    context-path: /identity

spring:
  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST}/identity
    url : ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds

