# Server configuration
server:
  port: 8888 # Port the gateway will run on
# Application specific configuration
app:
  api-prefix: /api
  swagger:
    paths: /api/identity/swagger-ui/**,/api/product/swagger-ui/**,/api/order/swagger-ui/**,/api/inventory/swagger-ui/**,/api/recombee-service/swagger-ui/**,/api/search-service/swagger-ui/**,/identity/v3/api-docs/**,/product/v3/api-docs/**,/order/v3/api-docs/**,/inventory/v3/api-docs/**,/recombee-service/v3/api-docs/**,/search-service/v3/api-docs/**
  services:
    # Define downstream microservice locations with environment variable overrides and defaults
    # Format: ${ENVIRONMENT_VARIABLE_NAME:defaultValue}
    identity: ${IDENTITY_HOST:http://localhost:8091}   # Identity service location
    product : ${PRODUCT_HOST:http://localhost:8088}   # Product service location
    order : ${ORDER_HOST:http://localhost:8082}     # Order service location
    inventory : ${INVENTORY_HOST:http://localhost:8083} # Inventory service location
    recombee : ${REC_HOST:http://localhost:8081}    # Recombee (recommendation) service location
    search : ${SEARCH_HOST:http://localhost:8081}    # Search service location
  security:
    product-paths:
      /api/product/**
    public-paths:
      /api/identity/auth/** # Authentication endpoints (login, register, refresh token)
    search-paths:
      /api/search-service/**
    recombee-paths:
      /api/recombee-service/**
    user-paths:
      /api/identity/users/create
    password-paths:
      /api/identity/password-reset/**

spring:
  application:
    name: api-gateway # Name of the application

  cloud:
    gateway:
      routes:
        # Route requests for the Identity Service
        - id: identity-service
          uri: ${app.services.identity} # Use variable defined in app.services
          predicates:
            # Match requests whose path starts with /api/identity/
            - Path=${app.api-prefix}/identity/**
          filters:
            # Remove the first path segment (/api) before forwarding
            # Corrected: Should strip /identity, not just /api if prefix is /api
            # If api-prefix is /api, StripPrefix=1 removes /api
            # If you want to remove /api/identity, use StripPrefix=2
            - StripPrefix=1 # Strips /api/identity

        # Route requests for the Product Service
        - id: product-service
          uri: ${app.services.product}
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=1 # Strips /api/product

        # Route requests for the Order Service
        - id: order-service
          uri: ${app.services.order}
          predicates:
            - Path=${app.api-prefix}/order/** # Match /api/order/**
          filters:
            - StripPrefix=1 # Strips /api/order

        # Route requests for the Inventory Service
        - id: inventory-service
          uri: ${app.services.inventory}
          predicates:
            - Path=${app.api-prefix}/inventory/** # Match /api/inventory/**
          filters:
            - StripPrefix=1 # Strips /api/inventory

        # Route requests for the Recombee (Recommendation) Service
        - id: recombee-service
          uri: ${app.services.recombee}
          predicates:
            # Note: Original path was /api/rec/**, ensure this matches your Recombee controller paths
            - Path=${app.api-prefix}/recombee-service/** # Match /api/recombee/** (Updated for consistency)
          filters:
            - RewritePath=${app.api-prefix}/recombee-service/(?<segment>.*), /recombee-service/${segment}


        # Route requests for the Search Service
        - id: search-service
          # Corrected URI reference if SEARCH_HOST points to 8081
          uri: ${app.services.search} # Should resolve to http://localhost:8081 by default
          predicates:
            - Path=${app.api-prefix}/search-service/** # Match /api/search/**
          filters:
            - RewritePath=${app.api-prefix}/search-service/(?<segment>.*), /search-service/${segment}

        - id: search-service-swagger
          uri: ${app.services.search} # Địa chỉ Swagger UI trên server khác
          predicates:
            - Path=${app.api-prefix}/search-service/swagger-ui/**
          filters:
            - StripPrefix=1
        - id: identity-service-swagger
          uri: ${app.services.identity} # Địa chỉ Swagger UI trên server khác
          predicates:
            - Path=${app.api-prefix}/identity/swagger-ui/**
          filters:
            - StripPrefix=1

        # Swagger UI for Product Service
        - id: product-service-swagger
          uri: ${app.services.product} # Địa chỉ Swagger UI trên server khác
          predicates:
            - Path=${app.api-prefix}/product/swagger-ui/**
          filters:
            - StripPrefix=1

        # Swagger UI for Order Service
        - id: order-service-swagger
          uri: ${app.services.order} # Địa chỉ Swagger UI trên server khác
          predicates:
            - Path=${app.api-prefix}/order/swagger-ui/**
          filters:
            - StripPrefix=1

        # Swagger UI for Inventory Service
        - id: inventory-service-swagger
          uri: ${app.services.inventory} # Địa chỉ Swagger UI trên server khác
          predicates:
            - Path=${app.api-prefix}/inventory/swagger-ui/**
          filters:
            - StripPrefix=1

        # Swagger UI for Recombee Service
        - id: recombee-service-swagger
          uri: ${app.services.recombee}  # The base URI of the Recombee service
          predicates:
            - Path=${app.api-prefix}/recombee-service/swagger-ui/**
          filters:
            - StripPrefix=1
        - id: identity-service-docs
          uri: ${app.services.identity}
          predicates:
            - Path=/identity/v3/api-docs/**

        - id: product-service-docs
          uri: ${app.services.product}
          predicates:
            - Path=/product/v3/api-docs/**

        - id: order-service-docs
          uri: ${app.services.order}
          predicates:
            - Path=/order/v3/api-docs/**

        - id: inventory-service-docs
          uri: ${app.services.inventory}
          predicates:
            - Path=/inventory/v3/api-docs/**

        - id: recombee-service-docs
          uri: ${app.services.recombee}
          predicates:
            - Path=/recombee-service/v3/api-docs/**

        - id: search-service-docs
          uri: ${app.services.search}
          predicates:
            - Path=/search-service/v3/api-docs/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.core.env: DEBUG
