server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id : identity-service
            uri : {http://localhost:8080:IDENTITY_PORT}
            predicates:
              - Path=${app.api-prefix}/identity/**
            filters:
              - StripPrefix=1
          - id: identity-service
            uri: { http://localhost:8081:CUSTOMER_PORT }
            predicates:
              - Path=${app.api-prefix}/customer/**
            filters:
              - StripPrefix=1