server:
  port: 8081
  servlet:
    context-path: /search-service

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  codec:
    max-in-memory-size: 50MB

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${DB_NAME}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: ${ES_URL}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    repositories:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 600000ms
      username: ${REDIS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
pinecone:
  api-key: pcsk_KUtgS_DZYC6qjTGi8VoK2rEEX99z41P48ug7oX2gAM6XbJvMMqm8aRkyfmzEfHVXeRpLB
  index-name: image-search
logging:
  level:
    org.springframework.web: DEBUG
image:
  processing:
    url: ${AI_SERVER_HOST}/extract-vector