server:
  port: 8081
  servlet:
    context-path: /search-service

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${DB_NAME}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    uris: ${ES_URL}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    repositories:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000
      username: ${REDIS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.web: DEBUG
