
app:
  services:
    product : http://localhost:8088/product
    user : http://localhost:8081/user
resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

caching:
  product-ttl: 3600 # 1 hour


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082