server:
  port: 8088
  servlet:
    context-path: /product

spring:
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:19755/railway
    username: postgres
    password: sxSaLoNJMmZOofAcxwUFORnbLJOmxPuN

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


