server:
  port: 8088
  servlet:
    context-path: /product

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${DB_NAME}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


