server:
  port: ${PRODUCT_PORT:8088}
  servlet:
    context-path: /product

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/product}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}

    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update

app:
  services:
    order: ${API_GATEWAY_ORDER_HOST:http://localhost:8082}/order